# Generated by Django 4.2.7 on 2025-11-07 22:54

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='short description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discount', max_digits=10, null=True, verbose_name='compare price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost price')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='low stock threshold')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20, verbose_name='condition')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='brand')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='weight (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='dimensions')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('total_views', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('search_rank', models.FloatField(default=0.0)),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='specifications')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='draft', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_sponsored', models.BooleanField(default=False, verbose_name='sponsored')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='shop name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shop_banners/', verbose_name='banner')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='region')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='district')),
                ('ward', models.CharField(blank=True, max_length=50, verbose_name='ward')),
                ('street_address', models.TextField(blank=True, verbose_name='street address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seller', models.OneToOneField(limit_choices_to={'user_type__in': ['seller', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='market.product', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'product view',
                'verbose_name_plural': 'product views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.shop', verbose_name='shop'),
        ),
        migrations.CreateModel(
            name='SponsoredRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='campaign title')),
                ('description', models.TextField(blank=True, verbose_name='campaign description')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='budget')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duration (days)')),
                ('target_regions', models.JSONField(blank=True, default=list, verbose_name='target regions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clicks_count', models.IntegerField(default=0)),
                ('impressions_count', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_requests', to='market.product', verbose_name='product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_requests', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
                ('target_categories', models.ManyToManyField(blank=True, to='market.category', verbose_name='target categories')),
            ],
            options={
                'verbose_name': 'sponsored request',
                'verbose_name_plural': 'sponsored requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='market_spon_status_318890_idx'), models.Index(fields=['seller', 'status'], name='market_spon_seller__109f7e_idx'), models.Index(fields=['product', 'status'], name='market_spon_product_26b6b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug', 'is_active'], name='market_shop_slug_18470e_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_verified', 'is_active'], name='market_shop_is_veri_ed8eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['rating', 'is_active'], name='market_shop_rating_c08701_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='market_sear_user_id_2fdbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['session_key', 'created_at'], name='market_sear_session_84f03b_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'viewed_at'], name='market_prod_product_33debc_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', 'viewed_at'], name='market_prod_user_id_7f469c_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='market_prod_ip_addr_c23ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='market_prod_product_fd4e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'is_active'], name='market_prod_slug_6d4ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='market_prod_categor_ab9e15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='market_prod_shop_id_e1b611_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'is_active'], name='market_prod_price_0a9158_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='market_prod_is_feat_c34158_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sponsored', 'is_active'], name='market_prod_is_spon_6a153a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='market_prod_status_61109c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at', 'is_active'], name='market_prod_created_850ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='market_cate_slug_5fce66_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='market_cate_parent__b4ba4a_idx'),
        ),
    ]
