# Generated by Django 4.2.7 on 2025-11-10 22:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='Uploadcare UUID for category image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(help_text='Uploadcare UUID for product image', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.CharField(blank=True, help_text='Uploadcare UUID for shop banner', max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.CharField(blank=True, help_text='Uploadcare UUID for shop logo', max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='market_prod_search__e31123_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['total_views', 'created_at'], name='market_prod_total_v_2e5906_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_rank', 'is_active'], name='market_prod_search__50102d_idx'),
        ),
    ]
