# Generated by Django 4.2.7 on 2025-11-07 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('order', 'Order Reference')], default='text', max_length=10, verbose_name='message type')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='file')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='orders.order')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('is_online', models.BooleanField(default=False, verbose_name='is online')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='last seen')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total sales')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monthly revenue')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='total products')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='total views')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='total customers')),
                ('repeat_customers', models.PositiveIntegerField(default=0, verbose_name='repeat customers')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('seller', models.OneToOneField(limit_choices_to={'user_type__in': ['seller', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'seller analytics',
                'verbose_name_plural': 'seller analytics',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='read at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True, verbose_name='room ID')),
                ('room_type', models.CharField(choices=[('buyer_seller', 'Buyer-Seller Chat'), ('support', 'Customer Support'), ('admin', 'Admin Chat')], default='buyer_seller', max_length=20, verbose_name='room type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='dashboard.ChatParticipant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat room',
                'verbose_name_plural': 'chat rooms',
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.chatroom'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='read_messages', through='dashboard.MessageReadReceipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chatroom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='sales')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='orders')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='new customers')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily stats',
                'verbose_name_plural': 'daily stats',
                'unique_together': {('seller', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('user', 'room')},
        ),
    ]
