# Generated by Django 4.2.7 on 2025-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.CharField(blank=True, help_text='Uploadcare UUID for file attachments', max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.CharField(blank=True, help_text='Uploadcare UUID for image files', max_length=255, null=True, verbose_name='image'),
        ),
    ]
