# Generated by Django 4.2.7 on 2025-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_banner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='store banner'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='store logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile picture'),
        ),
    ]
